apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

namePrefix: order-

commonLabels:
  app: order-service
  version: v1

commonAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8081"
  prometheus.io/path: "/actuator/prometheus"

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
