apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

commonLabels:
  component: service

resources:
  - product-service
  - order-service
  - inventory-service
  - notification-service
  - api-gateway
  - frontend
  - ingress.yaml
