server:
  http_listen_port: 3200

distributor:
  receivers:
    zipkin: {}

ingester:
  max_block_bytes: 104857600
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 720h # 30 days

metrics_generator:
  registry:
    external_labels:
      source: tempo

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

