spring.application.name=product-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://root:password@localhost:27017/product-service?authSource=admin}
springdoc.swagger-ui.path=/swagger-ui.html

# Observability
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://tempo:9411/api/v2/spans}

# Loki
loki.url=${LOKI_URL:http://loki:3100}

# Logging
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]