apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespaces:
  - infra
  - apps
  - observability

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: microservices-platform

commonAnnotations:
  metadata.platform/version: "1.0"

resources:
  - namespaces.yaml
  - apps
  - infra
  - observability
